name: CodeQL
on:
  push:
    branches:
      - main
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install CodeQL
        uses: github/codeql-action/setup@v2
        with:
          languages: javascript
      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v2
