name: Build & Push Docker Image

 

on:
  push:
    branches: [ main ]

 

env:
  tag: ${{ secrets.DOCKER_USERNAME }}:$(( $(date +%s) * 1000 ))

 

jobs:
  build:
    runs-on: ubuntu-latest

 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and tag Docker image
      run: |
        docker build -t ${{ env.tag }} .
        docker push ${{ env.tag }}
