name: Docker images
on: push
jobs:
build-project:
  name: Build Project
  runs-on: ubuntu-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Publish to GitHub Packages
    uses: docker/build-push-action@v1
    with:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      registry: docker.pkg.github.com
      repository: ${{ github.repository }}/webnext
      tags: latest, ${{ github.run_number }}
  - name: Push to Docker Hub
    uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repository: msusdev/webnext
      tags: latest, ${{ github.run_number }}
