name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "sailokeshbasava" --password-stdin
        docker image build -t sailokeshbasava/sai:latest .
        docker push sailokeshbasava/sai:latest
