ame: build and push images to docker hub

on:
  push:
    branches:
      - nini
  pull_request:
    branches:
      - nini
  # workflow_call:
  # workflow_dispatch:
   # inputs:
      # deploy_env: 
        # description: 'environment for the app to be deployed'
        # default: 'stage'
      # git_branch:
        # description: 'git branch of the mvp repo'
        # required: true
        # default: 'staging'
      # microservice_name:
        # description: 'MicroService name, the image to be built on!!'
        # required: true
        # default: ''
        # options:
        # - arcee
        # - bumi_scheduler
        # - bumi_worker
        # - diproxy
        # - diworker
        
      
jobs: 
  build&push:

    runs-on: ubuntu-latest


    steps:
    
    - name: Set TAG
      id: timestamp
      run: |
          Date=$(date +'%Y-%m-%d' | tr -d "-")
          Time=$(date +'%T' | tr -d ":")
          echo "::set-output name=TAG::$(echo "${Date}T${Time}Z")"

    
    - name: Check out my deployment
      uses: actions/checkout@v3
      with:
          repository: heeddata/heeddata_mvp
          
          
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: heeddatalabs
          password: CloudMonk@123

          
          
    - name: Build & Push Image
      #if: ${{ github.event.inputs.build_type == 'arcee' }} 
      uses: docker/build-push-action@v4
      with:
          context: heeddata_mvp/acree
          push: true
          file: heeddata_mvp/acree/Dockerfile
          tags: heeddatalabs/acree:${{ steps.timestamp.outputs.TAG}}
