name: Linter and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      TIMESTAMP: $ {{ date +%Y%m%d%H%M%S }}

    steps:
    - uses: actions/checkout@v3
    - name: Super-Linter
      uses: github/super-linter@v5.0.0
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: 
        export timestamp=$(date +%Y%m%d%H%M%S)
        echo "::set-output name=timestamp::$timestamp"
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "sailokeshbasava" --password-stdin
        docker image build -t sailokeshbasava/new:$timestamp .
        docker push sailokeshbasava/new:$timestamp
