name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Node.js and npm
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Install Python and pip
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install dependencies for Node.js
      - name: Install Node.js dependencies
        run: npm ci

      # Run ESLint for JavaScript files
      - name: Run ESLint
        run: npx eslint .

      # Install dependencies for Python
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Run Flake8 for Python files
      - name: Run Flake8
        run: flake8 .
