name: Linter and pushing images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Super-Linter
      uses: github/super-linter@v5.0.0
      with:
        repo-token: ${{ secrets.GIT_TOKEN }}
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@master
      with:
        dockerfile: "Dockerfile"
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: master
