name: Haskell Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
jobs:
  hlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HLINT_ACTION_LOG_LEVEL: debug
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up HLint
        uses: rwe/actions-hlint-setup@v1

      - name: Haskell Lint
        uses: rwe/actions-hlint-run@v2
