name: Python Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install flake8

      - name: Run lint
        run: flake8
        
      - uses: actions/checkout@v1
      - name: Use Node.js "13.x"
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Installing Node Dependencies
        run: |
          npm install
          cd unit_testing
          npm install
