name: Python Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install flake8

      - name: Run lint
        run: flake8

      - name: checkoput code js
        uses: actions/checkout@v2
        
      - name: Install modules
        run: yarn
        
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
