name: Linter file
on:
  push:
    branches:
      - master # Specify the branch you want to trigger the workflow on

jobs:
  lint:
    runs-on: ubuntu-latest # Specify the operating system for the workflow to run on

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Checkout the repository code

    - name: Install dependencies
      run: npm ci # Install any dependencies required for your linter

    - name: Run linter
      run: npm run lint # Run your linter command here

    - name: Create pull request
      if: success() # Only create pull request if the linting is successful
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GIT_TOKEN }} # Required for creating pull request
        branch: lint-fixes # Specify the branch name for the pull request
        commit-message: "Fix linting issues"
        title: "Fix linting issues"
        body: "This pull request fixes linting issues found in the code."

    - name: Merge pull request
      if: success() # Only merge pull request if it was created successfully
      uses: pullreminders/merge-action@v5
      with:
        token: ${{ secrets.GIT_TOKEN }} # Required for merging pull request
        pull_request: ${{ steps.create_pull_request.outputs.pull_request_number }} # Reference to the created pull request

    - name: Delete branch
      if: success() # Only delete branch if pull request was merged successfully
      run: |
        git checkout master # Switch to the target branch
        git branch -d lint-fixes # Delete the lint-fixes branch
